name: Build NuGet package

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  MSBuildEnableWorkloadResolver: false

jobs:
  build:
    strategy:
      matrix:
        toolset: [x64]
        config: [Debug, Release]

    runs-on: windows-latest
    name: Windows 10, ${{ matrix.config }} ${{ matrix.toolset }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install python packages
      working-directory: ${{github.workspace}}
      run: python -m pip install -r ./BuildTools/.NET/requirements.txt

    - name: Build and run
      working-directory: ${{github.workspace}}
      run: python ./BuildTools/.NET/dotnet-build-package.py -c ${{matrix.config}} -s ./BuildTools/.NET/dotnet-build-settings.json -d ./ --free-memory

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: DiligentCore-${{ matrix.config }}-${{ matrix.toolset }}
        path: build/.NET/Graphics/GraphicsEngine.NET/bin/${{matrix.config}}
        retention-days: 90
